### ISSUE TITLE
opore and gold

### ISSUE THREAD

**Issue by JasperChaseTOQ** [XenoForce/No-Grinding-Mod#2]
whats with the opore and gold walls/conveyor and it has a move speed of 0 items

**Comment by XenoForce** [comment]
1) When a wall block was damaged by the enemy, it is faster to replace the damaged wall block with a wall block of a different type. This overrides one wall block type with another wall block type. 

If you only have access to 1 wall block type, then the process is much slower: you have to first remove the old damaged wall block, and then replace it with the same wall block type.  This takes two steps.

If you have access to more than 1 type of wall block, then it is only one step: Just replace the damaged wall block, with a wall block of a different type. And you end up with an undamaged wall block.

2) The conveyor speed of 0.15 is actually pretty fast.
